services:
  - type: web
    name: utility
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: SUPABASE_URL
        value: https://aqsjuaescqmbzyhwnlbv.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxc2p1YWVzY3FtYnp5aHdubGJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMzMjY3MzIsImV4cCI6MjA3ODkwMjczMn0.D_5_HnrsPBUK4UNI3BT8y6aeUF897r_JHoG5r9WeUOo
      - key: SECRET_KEY
        value: uka-bill-utility-secret-2026