services:
  - type: web
    name: utility-bills-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        value: ministry-of-education-brunei-2024
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1
